version: 2
updates:
  # Backend npm packages
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Bunde all backend npm updates into a single PR
    groups:
      backend-deps:
        patterns:
          - "*"
  # Frontend npm packages
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Bundle all frontend npm updates into a single PR
    groups:
      frontend-deps:
        patterns:
          - "*"
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
