services:
  frontend:
    build: ./frontend
    container_name: diagram_frontend
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - obs-network
  backend:
    build: ./backend
    container_name: diagram_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - obs-network

networks:
  obs-network:
    external: true
