services:
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: diagram_frontend_dev
    ports:
      - "5273:5273"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      target: dev
    container_name: diagram_backend_dev
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
  postgres:
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    ports:
      - "5432:5432"
