services:
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: diagram_frontend_dev
    ports:
      - "5223:5223"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      target: dev
    container_name: diagram_backend_dev
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
  postgres:
    ports:
      - "5432:5432"
