services:
  frontend:
    build: ./frontend
    container_name: diagram_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - obs-network

  backend:
    build: ./backend
    container_name: diagram_backend
    ports:
      - "5050:5050"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - obs-network

  postgres:
    image: postgres:16-alpine
    container_name: diagram_postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: diagramdb
      POSTGRES_USER: diagram
      POSTGRES_PASSWORD: diagram
    volumes:
      - diagram_postgres_data:/var/lib/postgresql/data
    networks:
      - obs-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.19.1
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_URI: "diagram_postgres:5432/diagramdb?sslmode=disable"
      DATA_SOURCE_USER: diagram
      DATA_SOURCE_PASS: diagram
    ports:
      - "9187:9187"
    networks:
      - obs-network
    depends_on:
      - postgres

networks:
  obs-network:
    driver: bridge

volumes:
  diagram_postgres_data:
