services:
  frontend:
    build: ./frontend
    container_name: diagram_frontend
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - diagram_website
  backend:
    build: ./backend
    container_name: diagram_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - diagram_website

networks:
  diagram_website:
    driver: bridge
