groups:
  - name: infrastructure_alerts
    rules:
      - alert: InstanceDown
        expr: up{job="alloy"} == 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Instance Down"
          description: "The alloy container is unreachable."

      - alert: DatabaseDown
        expr: pg_up == 0 or up{job="postgres"} == 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Database Down"
          description: "The diagram_postgres database or its exporter is completely unreachable."
